version: '3'
services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web:/var/www/html"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php
      - mysqldb

  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    container_name: php
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/php/conf.d/php.ini"
      - "./web:/var/www/html"
  
  composer:
    image: painless/composer
    container_name: composer
    volumes:
      - "./web:/app"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysqldb
      
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./etc/mysql/data:/var/lib/mysql"